* Pandas のデータ構造 は、Series と DataFrame
* Series は、1次元
* DataFrame は、複数の Series からなる

In [1]:
import pandas as pd

s1 = pd.Series([1,2,3,4,5])
print(type(s1))
print(s1)

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
df1 = pd.DataFrame({
    'id' : [1,2,3],
    'name' : ['bob','alice','john'],
    'sex' : ['m','f','x']
})
print(type(df1))
print(df1)

<class 'pandas.core.frame.DataFrame'>
   id   name sex
0   1    bob   m
1   2  alice   f
2   3   john   x

* DataFrame のカラム名は、df.columns で取得できる
* 1行分のデータは、[name] [[name]] で取得できる
    * [name] で取得すると Series が取得できる
    * [[name]] で取得すると 1行の DataFrame が取得できる

In [3]:
print(df1.columns)

print(type(df1.name))
print(df1.name)

print(type(df1['name']))
print(df1['name'])

print(type(df1[['name']]))
print(df1[['name']])

Index(['id', 'name', 'sex'], dtype='object')
<class 'pandas.core.series.Series'>
0      bob
1    alice
2     john
Name: name, dtype: object
<class 'pandas.core.series.Series'>
0      bob
1    alice
2     john
Name: name, dtype: object
<class 'pandas.core.frame.DataFrame'>
    name
0    bob
1  alice
2   john

* pd.read_csv() で csv を読み込むことができる
* そのほかに、Excel、Data Base、などから読み込むことができる
* df.head() で先頭５行表示。引数で指定可
* df.tail() で末尾５行表示。引数で指定可

In [5]:
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')

print(iris.head())
print(iris.tail())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

* DataFrame の一部を取り出す
* df.loc[row:row,col:col] は、行インデックスと列インデックスで DataFrame の一部を DataFrame として切り出す
* df.iloc[row_num:row_num, col_num:col_num] は、行番号と列番号で DataFrame の一部を DataFrame として切り出す
* df.at[row,col] は、行インデックスと列インデックスで指定した要素を切り出す
* df.at[row_num, col_num] は、行番号と列番号で要素を切り出す

In [11]:
print(iris.loc[15:20,'sepal_length':'petal_width'])
print(iris.iloc[25:30,0:4])
print(iris.at[15,'sepal_width'])
print(iris.iat[15,1])

    sepal_length  sepal_width  petal_length  petal_width
15           5.7          4.4           1.5          0.4
16           5.4          3.9           1.3          0.4
17           5.1          3.5           1.4          0.3
18           5.7          3.8           1.7          0.3
19           5.1          3.8           1.5          0.3
20           5.4          3.4           1.7          0.2
    sepal_length  sepal_width  petal_length  petal_width
25           5.0          3.0           1.6          0.2
26           5.0          3.4           1.6          0.4
27           5.2          3.5           1.5          0.2
28           5.2          3.4           1.4          0.2
29           4.7          3.2           1.6          0.2
4.4
4.4

* df.query() で、行の絞り込みができる
* 欠損値の排除などに使えそうだ

In [14]:
iris.query('sepal_length > 6.5')

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
52            6.9          3.1           4.9          1.5  versicolor
58            6.6          2.9           4.6          1.3  versicolor
65            6.7          3.1           4.4          1.4  versicolor
75            6.6          3.0           4.4          1.4  versicolor
76            6.8          2.8           4.8          1.4  versicolor
77            6.7          3.0           5.0          1.7  versicolor
86            6.7          3.1           4.7          1.5  versicolor
102           7.1          3.0           5.9          2.1   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
112           6.8          3.0           5.5          2.1   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
122           7.7          2.8           6.7          2.0   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
135           7.7          3.0           6.1          2.3   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica

* df.to_csv() で DataFrame を csv に書き出すことができる

In [17]:
iris.query('sepal_length > 6.5').to_csv('filtered_iris.csv', encoding="UTF-8")